// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package models

import (
	"context"
)

const countCertificates = `-- name: CountCertificates :one
SELECT COUNT(*) FROM certificates
`

func (q *Queries) CountCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCertificates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCertificatesByFQDN = `-- name: CountCertificatesByFQDN :one
SELECT COUNT(*) FROM certificates WHERE fqdn_id = ?
`

func (q *Queries) CountCertificatesByFQDN(ctx context.Context, fqdnID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCertificatesByFQDN, fqdnID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates WHERE id = ?
`

func (q *Queries) GetCertificate(ctx context.Context, id string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.FqdnID,
		&i.Serial,
		&i.IssuerCa,
		&i.SubjectCn,
		&i.Sans,
		&i.NotBefore,
		&i.NotAfter,
		&i.DiscoveredAt,
		&i.Source,
		&i.IssuerName,
		&i.Revoked,
	)
	return i, err
}

const getCertificateBySerial = `-- name: GetCertificateBySerial :one
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates WHERE fqdn_id = ? AND serial = ?
`

type GetCertificateBySerialParams struct {
	FqdnID string `json:"fqdn_id"`
	Serial string `json:"serial"`
}

func (q *Queries) GetCertificateBySerial(ctx context.Context, arg GetCertificateBySerialParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificateBySerial, arg.FqdnID, arg.Serial)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.FqdnID,
		&i.Serial,
		&i.IssuerCa,
		&i.SubjectCn,
		&i.Sans,
		&i.NotBefore,
		&i.NotAfter,
		&i.DiscoveredAt,
		&i.Source,
		&i.IssuerName,
		&i.Revoked,
	)
	return i, err
}

const insertCertificate = `-- name: InsertCertificate :one
INSERT OR IGNORE INTO certificates
    (id, fqdn_id, serial, issuer_ca, issuer_name, subject_cn, sans, not_before, not_after, discovered_at, source, revoked)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked
`

type InsertCertificateParams struct {
	ID           string `json:"id"`
	FqdnID       string `json:"fqdn_id"`
	Serial       string `json:"serial"`
	IssuerCa     string `json:"issuer_ca"`
	IssuerName   string `json:"issuer_name"`
	SubjectCn    string `json:"subject_cn"`
	Sans         string `json:"sans"`
	NotBefore    string `json:"not_before"`
	NotAfter     string `json:"not_after"`
	DiscoveredAt string `json:"discovered_at"`
	Source       string `json:"source"`
	Revoked      bool   `json:"revoked"`
}

func (q *Queries) InsertCertificate(ctx context.Context, arg InsertCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, insertCertificate,
		arg.ID,
		arg.FqdnID,
		arg.Serial,
		arg.IssuerCa,
		arg.IssuerName,
		arg.SubjectCn,
		arg.Sans,
		arg.NotBefore,
		arg.NotAfter,
		arg.DiscoveredAt,
		arg.Source,
		arg.Revoked,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.FqdnID,
		&i.Serial,
		&i.IssuerCa,
		&i.SubjectCn,
		&i.Sans,
		&i.NotBefore,
		&i.NotAfter,
		&i.DiscoveredAt,
		&i.Source,
		&i.IssuerName,
		&i.Revoked,
	)
	return i, err
}

const listCertificates = `-- name: ListCertificates :many
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates ORDER BY discovered_at DESC LIMIT ? OFFSET ?
`

type ListCertificatesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.FqdnID,
			&i.Serial,
			&i.IssuerCa,
			&i.SubjectCn,
			&i.Sans,
			&i.NotBefore,
			&i.NotAfter,
			&i.DiscoveredAt,
			&i.Source,
			&i.IssuerName,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByFQDN = `-- name: ListCertificatesByFQDN :many
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates WHERE fqdn_id = ?
ORDER BY discovered_at DESC LIMIT ? OFFSET ?
`

type ListCertificatesByFQDNParams struct {
	FqdnID string `json:"fqdn_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListCertificatesByFQDN(ctx context.Context, arg ListCertificatesByFQDNParams) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listCertificatesByFQDN, arg.FqdnID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.FqdnID,
			&i.Serial,
			&i.IssuerCa,
			&i.SubjectCn,
			&i.Sans,
			&i.NotBefore,
			&i.NotAfter,
			&i.DiscoveredAt,
			&i.Source,
			&i.IssuerName,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCAs = `-- name: ListDistinctCAs :many
SELECT DISTINCT issuer_ca FROM certificates WHERE issuer_ca != '' ORDER BY issuer_ca
`

func (q *Queries) ListDistinctCAs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctCAs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var issuer_ca string
		if err := rows.Scan(&issuer_ca); err != nil {
			return nil, err
		}
		items = append(items, issuer_ca)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
