// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package models

import (
	"context"
)

const addFQDNChannel = `-- name: AddFQDNChannel :exec
INSERT OR IGNORE INTO fqdn_channels (fqdn_id, channel_id) VALUES (?, ?)
`

type AddFQDNChannelParams struct {
	FqdnID    string `json:"fqdn_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) AddFQDNChannel(ctx context.Context, arg AddFQDNChannelParams) error {
	_, err := q.db.ExecContext(ctx, addFQDNChannel, arg.FqdnID, arg.ChannelID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO notification_channels (id, name, type, config, enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type CreateChannelParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const deleteFQDNChannels = `-- name: DeleteFQDNChannels :exec
DELETE FROM fqdn_channels WHERE fqdn_id = ?
`

func (q *Queries) DeleteFQDNChannels(ctx context.Context, fqdnID string) error {
	_, err := q.db.ExecContext(ctx, deleteFQDNChannels, fqdnID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, type, config, enabled, created_at, updated_at FROM notification_channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFQDNChannelIDs = `-- name: GetFQDNChannelIDs :many
SELECT channel_id FROM fqdn_channels WHERE fqdn_id = ?
`

func (q *Queries) GetFQDNChannelIDs(ctx context.Context, fqdnID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFQDNChannelIDs, fqdnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFQDNChannels = `-- name: GetFQDNChannels :many
SELECT nc.id, nc.name, nc.type, nc.config, nc.enabled, nc.created_at, nc.updated_at FROM notification_channels nc
INNER JOIN fqdn_channels fc ON fc.channel_id = nc.id
WHERE fc.fqdn_id = ?
ORDER BY nc.name
`

func (q *Queries) GetFQDNChannels(ctx context.Context, fqdnID string) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, getFQDNChannels, fqdnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, type, config, enabled, created_at, updated_at FROM notification_channels ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE notification_channels
SET name       = ?,
    type       = ?,
    config     = ?,
    enabled    = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, name, type, config, enabled, created_at, updated_at
`

type UpdateChannelParams struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled bool   `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
