// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fqdns.sql

package models

import (
	"context"
)

const createFQDN = `-- name: CreateFQDN :one
INSERT INTO fqdns (id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id, created_at, updated_at
`

type CreateFQDNParams struct {
	ID                   string  `json:"id"`
	Fqdn                 string  `json:"fqdn"`
	IncludeSubdomains    bool    `json:"include_subdomains"`
	Enabled              bool    `json:"enabled"`
	NotificationsEnabled bool    `json:"notifications_enabled"`
	ScheduleID           *string `json:"schedule_id"`
}

func (q *Queries) CreateFQDN(ctx context.Context, arg CreateFQDNParams) (Fqdn, error) {
	row := q.db.QueryRowContext(ctx, createFQDN,
		arg.ID,
		arg.Fqdn,
		arg.IncludeSubdomains,
		arg.Enabled,
		arg.NotificationsEnabled,
		arg.ScheduleID,
	)
	var i Fqdn
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.IncludeSubdomains,
		&i.Enabled,
		&i.NotificationsEnabled,
		&i.ScheduleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFQDN = `-- name: DeleteFQDN :exec
DELETE FROM fqdns WHERE id = ?
`

func (q *Queries) DeleteFQDN(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFQDN, id)
	return err
}

const getFQDN = `-- name: GetFQDN :one
SELECT id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id, created_at, updated_at FROM fqdns WHERE id = ?
`

func (q *Queries) GetFQDN(ctx context.Context, id string) (Fqdn, error) {
	row := q.db.QueryRowContext(ctx, getFQDN, id)
	var i Fqdn
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.IncludeSubdomains,
		&i.Enabled,
		&i.NotificationsEnabled,
		&i.ScheduleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFQDNByName = `-- name: GetFQDNByName :one
SELECT id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id, created_at, updated_at FROM fqdns WHERE fqdn = ?
`

func (q *Queries) GetFQDNByName(ctx context.Context, fqdn string) (Fqdn, error) {
	row := q.db.QueryRowContext(ctx, getFQDNByName, fqdn)
	var i Fqdn
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.IncludeSubdomains,
		&i.Enabled,
		&i.NotificationsEnabled,
		&i.ScheduleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledFQDNs = `-- name: ListEnabledFQDNs :many
SELECT id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id, created_at, updated_at FROM fqdns WHERE enabled = 1 ORDER BY fqdn
`

func (q *Queries) ListEnabledFQDNs(ctx context.Context) ([]Fqdn, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledFQDNs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fqdn
	for rows.Next() {
		var i Fqdn
		if err := rows.Scan(
			&i.ID,
			&i.Fqdn,
			&i.IncludeSubdomains,
			&i.Enabled,
			&i.NotificationsEnabled,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFQDNs = `-- name: ListFQDNs :many
SELECT id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id, created_at, updated_at FROM fqdns ORDER BY fqdn
`

func (q *Queries) ListFQDNs(ctx context.Context) ([]Fqdn, error) {
	rows, err := q.db.QueryContext(ctx, listFQDNs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fqdn
	for rows.Next() {
		var i Fqdn
		if err := rows.Scan(
			&i.ID,
			&i.Fqdn,
			&i.IncludeSubdomains,
			&i.Enabled,
			&i.NotificationsEnabled,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFQDN = `-- name: UpdateFQDN :one
UPDATE fqdns
SET fqdn                  = ?,
    include_subdomains    = ?,
    enabled               = ?,
    notifications_enabled = ?,
    schedule_id           = ?,
    updated_at            = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, fqdn, include_subdomains, enabled, notifications_enabled, schedule_id, created_at, updated_at
`

type UpdateFQDNParams struct {
	Fqdn                 string  `json:"fqdn"`
	IncludeSubdomains    bool    `json:"include_subdomains"`
	Enabled              bool    `json:"enabled"`
	NotificationsEnabled bool    `json:"notifications_enabled"`
	ScheduleID           *string `json:"schedule_id"`
	ID                   string  `json:"id"`
}

func (q *Queries) UpdateFQDN(ctx context.Context, arg UpdateFQDNParams) (Fqdn, error) {
	row := q.db.QueryRowContext(ctx, updateFQDN,
		arg.Fqdn,
		arg.IncludeSubdomains,
		arg.Enabled,
		arg.NotificationsEnabled,
		arg.ScheduleID,
		arg.ID,
	)
	var i Fqdn
	err := row.Scan(
		&i.ID,
		&i.Fqdn,
		&i.IncludeSubdomains,
		&i.Enabled,
		&i.NotificationsEnabled,
		&i.ScheduleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
