// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"
)

type Certificate struct {
	ID           string `json:"id"`
	FqdnID       string `json:"fqdn_id"`
	Serial       string `json:"serial"`
	IssuerCa     string `json:"issuer_ca"`
	SubjectCn    string `json:"subject_cn"`
	Sans         string `json:"sans"`
	NotBefore    string `json:"not_before"`
	NotAfter     string `json:"not_after"`
	DiscoveredAt string `json:"discovered_at"`
	Source       string `json:"source"`
	IssuerName   string `json:"issuer_name"`
	Revoked      bool   `json:"revoked"`
}

type Fqdn struct {
	ID                   string  `json:"id"`
	Fqdn                 string  `json:"fqdn"`
	IncludeSubdomains    bool    `json:"include_subdomains"`
	Enabled              bool    `json:"enabled"`
	NotificationsEnabled bool    `json:"notifications_enabled"`
	ScheduleID           *string `json:"schedule_id"`
	CreatedAt            string  `json:"created_at"`
	UpdatedAt            string  `json:"updated_at"`
}

type FqdnChannel struct {
	FqdnID    string `json:"fqdn_id"`
	ChannelID string `json:"channel_id"`
}

type NotificationChannel struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Config    string `json:"config"`
	Enabled   bool   `json:"enabled"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Schedule struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CronExpr  string `json:"cron_expr"`
	IsDefault bool   `json:"is_default"`
	Enabled   bool   `json:"enabled"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Setting struct {
	ID                        int64     `json:"id"`
	AuthEnabled               bool      `json:"auth_enabled"`
	Username                  *string   `json:"username"`
	PasswordHash              *string   `json:"password_hash"`
	ApiTokenProtectionEnabled bool      `json:"api_token_protection_enabled"`
	ApiToken                  *string   `json:"api_token"`
	Theme                     string    `json:"theme"`
	SslmateApiKey             string    `json:"sslmate_api_key"`
	DefaultScheduleID         *string   `json:"default_schedule_id"`
	UpdatedAt                 time.Time `json:"updated_at"`
}
