// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_log.sql

package models

import (
	"context"
)

const getCertsExpiringBefore = `-- name: GetCertsExpiringBefore :many
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates
WHERE fqdn_id = ? AND revoked = 0
  AND not_after > ? AND not_after <= ?
`

type GetCertsExpiringBeforeParams struct {
	FqdnID     string `json:"fqdn_id"`
	NotAfter   string `json:"not_after"`
	NotAfter_2 string `json:"not_after_2"`
}

func (q *Queries) GetCertsExpiringBefore(ctx context.Context, arg GetCertsExpiringBeforeParams) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getCertsExpiringBefore, arg.FqdnID, arg.NotAfter, arg.NotAfter_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.FqdnID,
			&i.Serial,
			&i.IssuerCa,
			&i.SubjectCn,
			&i.Sans,
			&i.NotBefore,
			&i.NotAfter,
			&i.DiscoveredAt,
			&i.Source,
			&i.IssuerName,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredCerts = `-- name: GetExpiredCerts :many
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates
WHERE fqdn_id = ? AND revoked = 0 AND not_after <= ?
`

type GetExpiredCertsParams struct {
	FqdnID   string `json:"fqdn_id"`
	NotAfter string `json:"not_after"`
}

func (q *Queries) GetExpiredCerts(ctx context.Context, arg GetExpiredCertsParams) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredCerts, arg.FqdnID, arg.NotAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.FqdnID,
			&i.Serial,
			&i.IssuerCa,
			&i.SubjectCn,
			&i.Sans,
			&i.NotBefore,
			&i.NotAfter,
			&i.DiscoveredAt,
			&i.Source,
			&i.IssuerName,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreviousCertForFQDN = `-- name: GetPreviousCertForFQDN :one
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates
WHERE fqdn_id = ? AND serial != ?
ORDER BY discovered_at DESC LIMIT 1
`

type GetPreviousCertForFQDNParams struct {
	FqdnID string `json:"fqdn_id"`
	Serial string `json:"serial"`
}

func (q *Queries) GetPreviousCertForFQDN(ctx context.Context, arg GetPreviousCertForFQDNParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getPreviousCertForFQDN, arg.FqdnID, arg.Serial)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.FqdnID,
		&i.Serial,
		&i.IssuerCa,
		&i.SubjectCn,
		&i.Sans,
		&i.NotBefore,
		&i.NotAfter,
		&i.DiscoveredAt,
		&i.Source,
		&i.IssuerName,
		&i.Revoked,
	)
	return i, err
}

const getRevokedCerts = `-- name: GetRevokedCerts :many
SELECT id, fqdn_id, serial, issuer_ca, subject_cn, sans, not_before, not_after, discovered_at, source, issuer_name, revoked FROM certificates
WHERE fqdn_id = ? AND revoked = 1
`

func (q *Queries) GetRevokedCerts(ctx context.Context, fqdnID string) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getRevokedCerts, fqdnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.FqdnID,
			&i.Serial,
			&i.IssuerCa,
			&i.SubjectCn,
			&i.Sans,
			&i.NotBefore,
			&i.NotAfter,
			&i.DiscoveredAt,
			&i.Source,
			&i.IssuerName,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logNotification = `-- name: LogNotification :exec
INSERT OR IGNORE INTO notification_log (id, fqdn_id, cert_id, event)
VALUES (?, ?, ?, ?)
`

type LogNotificationParams struct {
	ID     string `json:"id"`
	FqdnID string `json:"fqdn_id"`
	CertID string `json:"cert_id"`
	Event  string `json:"event"`
}

func (q *Queries) LogNotification(ctx context.Context, arg LogNotificationParams) error {
	_, err := q.db.ExecContext(ctx, logNotification,
		arg.ID,
		arg.FqdnID,
		arg.CertID,
		arg.Event,
	)
	return err
}

const wasNotificationSent = `-- name: WasNotificationSent :one
SELECT COUNT(*) > 0 FROM notification_log
WHERE fqdn_id = ? AND cert_id = ? AND event = ?
  AND sent_at > strftime('%Y-%m-%dT%H:%M:%SZ', datetime('now', '-24 hours'))
`

type WasNotificationSentParams struct {
	FqdnID string `json:"fqdn_id"`
	CertID string `json:"cert_id"`
	Event  string `json:"event"`
}

func (q *Queries) WasNotificationSent(ctx context.Context, arg WasNotificationSentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, wasNotificationSent, arg.FqdnID, arg.CertID, arg.Event)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
