// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package models

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (id, name, cron_expr, is_default, enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, cron_expr, is_default, enabled, created_at, updated_at
`

type CreateScheduleParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CronExpr  string `json:"cron_expr"`
	IsDefault bool   `json:"is_default"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.ID,
		arg.Name,
		arg.CronExpr,
		arg.IsDefault,
		arg.Enabled,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const getDefaultSchedule = `-- name: GetDefaultSchedule :one
SELECT id, name, cron_expr, is_default, enabled, created_at, updated_at FROM schedules WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultSchedule(ctx context.Context) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getDefaultSchedule)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, name, cron_expr, is_default, enabled, created_at, updated_at FROM schedules WHERE id = ?
`

func (q *Queries) GetSchedule(ctx context.Context, id string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, name, cron_expr, is_default, enabled, created_at, updated_at FROM schedules ORDER BY name
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpr,
			&i.IsDefault,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultSchedules = `-- name: UnsetDefaultSchedules :exec
UPDATE schedules SET is_default = 0 WHERE is_default = 1
`

func (q *Queries) UnsetDefaultSchedules(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unsetDefaultSchedules)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET name      = ?,
    cron_expr = ?,
    is_default = ?,
    enabled   = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
RETURNING id, name, cron_expr, is_default, enabled, created_at, updated_at
`

type UpdateScheduleParams struct {
	Name      string `json:"name"`
	CronExpr  string `json:"cron_expr"`
	IsDefault bool   `json:"is_default"`
	Enabled   bool   `json:"enabled"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, updateSchedule,
		arg.Name,
		arg.CronExpr,
		arg.IsDefault,
		arg.Enabled,
		arg.ID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpr,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
