// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package models

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, auth_enabled, username, password_hash, api_token_protection_enabled, api_token, theme, sslmate_api_key, default_schedule_id, updated_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.AuthEnabled,
		&i.Username,
		&i.PasswordHash,
		&i.ApiTokenProtectionEnabled,
		&i.ApiToken,
		&i.Theme,
		&i.SslmateApiKey,
		&i.DefaultScheduleID,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET auth_enabled                 = ?,
    username                     = ?,
    password_hash                = ?,
    api_token_protection_enabled = ?,
    api_token                    = ?,
    theme                        = ?,
    sslmate_api_key              = ?,
    default_schedule_id          = ?,
    updated_at                   = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = 1
RETURNING id, auth_enabled, username, password_hash, api_token_protection_enabled, api_token, theme, sslmate_api_key, default_schedule_id, updated_at
`

type UpdateSettingsParams struct {
	AuthEnabled               bool    `json:"auth_enabled"`
	Username                  *string `json:"username"`
	PasswordHash              *string `json:"password_hash"`
	ApiTokenProtectionEnabled bool    `json:"api_token_protection_enabled"`
	ApiToken                  *string `json:"api_token"`
	Theme                     string  `json:"theme"`
	SslmateApiKey             string  `json:"sslmate_api_key"`
	DefaultScheduleID         *string `json:"default_schedule_id"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.AuthEnabled,
		arg.Username,
		arg.PasswordHash,
		arg.ApiTokenProtectionEnabled,
		arg.ApiToken,
		arg.Theme,
		arg.SslmateApiKey,
		arg.DefaultScheduleID,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.AuthEnabled,
		&i.Username,
		&i.PasswordHash,
		&i.ApiTokenProtectionEnabled,
		&i.ApiToken,
		&i.Theme,
		&i.SslmateApiKey,
		&i.DefaultScheduleID,
		&i.UpdatedAt,
	)
	return i, err
}
